##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##


docker_config: &docker_config
  docker:
    - image: sas42/ds2-build-env:2018-09-12_17-18-00

configure_step: &configure_step
  run:
    name: Configure
    command: mkdir build && cd build && cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../Support/CMake/Toolchain-${TARGET-${CIRCLE_JOB}}.cmake ${EXTRA_CMAKE_ARGS-} ..

build_step: &build_step
  run:
    name: Build
    command: ninja -C build -v

test_step: &test_step
  run:
    name: Test
    command: cd build && ../Support/Scripts/run-${DEBUGGER-lldb}-tests.sh --log

check_dirty_step: &check_dirty_step
  run:
    name: Check for dirty state
    command: git --no-pager diff --exit-code

start_android_emulator_step: &start_android_emulator_step
  run:
    name: Start Android emulator
    command: ./Support/Scripts/start-android-emulator.py --target ${TARGET}
    background: true

build_only_defaults: &build_only_defaults
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step

build_and_test_defaults: &build_and_test_defaults
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step
    - *test_step

build_and_test_android: &build_and_test_android
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step
    - *start_android_emulator_step
    - *test_step

version: 2
jobs:
  Linux-X86-Clang:
    <<: *build_and_test_defaults
  Linux-X86-Clang-platform:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86-Clang
      PLATFORM: 1
  Linux-X86_64-Clang:
    <<: *build_and_test_defaults
  Linux-X86_64-Clang-platform:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86_64-Clang
      PLATFORM: 1
  Linux-X86_64-GDB:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86_64
      DEBUGGER: gdb
      GDB_TESTS: "gdb.base/break;gdb.base/printcmds;gdb.base/step-bt"
  Linux-X86_64-GDB-Clang:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86_64-Clang
      DEBUGGER: gdb
      GDB_TESTS: "gdb.base/break;gdb.base/printcmds;gdb.base/step-bt"
  Android-ARM:
    <<: *build_and_test_android
    environment:
      PLATFORM: 1
      TARGET: Android-ARM
      EXTRA_CMAKE_ARGS: "-DCMAKE_SYSTEM_VERSION=21"
  Android-ARM-16:
    <<: *build_only_defaults
    environment:
      TARGET: Android-ARM
      EXTRA_CMAKE_ARGS: "-DCMAKE_SYSTEM_VERSION=16"
  Android-ARM64:
    <<: *build_and_test_android
    environment:
      PLATFORM: 1
      TARGET: Android-ARM64
      EXTRA_CMAKE_ARGS: "-DCMAKE_SYSTEM_VERSION=24"
  Android-X86:
    <<: *build_only_defaults
  Android-X86-16:
    <<: *build_only_defaults
    environment:
      TARGET: Android-X86
      EXTRA_CMAKE_ARGS: "-DCMAKE_SYSTEM_VERSION=16"
  Android-X86_64:
    <<: *build_only_defaults
  Tizen-X86:
    <<: *build_only_defaults
  Tizen-ARM:
    <<: *build_only_defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - Linux-X86-Clang
      - Linux-X86-Clang-platform
      - Linux-X86_64-Clang
      - Linux-X86_64-Clang-platform
      - Linux-X86_64-GDB
      - Linux-X86_64-GDB-Clang
      - Android-ARM
      - Android-ARM-16
      - Android-ARM64
      - Android-X86
      - Android-X86-16
      - Android-X86_64
      - Tizen-X86
      - Tizen-ARM
